// DOM tests only; no browser navigation, network, or real reviewer decisions.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const dir=process.argv[2];if(!dir)throw Error('Usage: node tests/ui.cjs ACCEPTANCE_OUTPUT_DIR');
const raw=fs.readFileSync(path.join(dir,'small-reference-list.review.html'),'utf8');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(raw,{runScripts:'dangerously',url:'https://test.invalid/',virtualConsole:vc});const doc=dom.window.document;
assert.equal(doc.querySelectorAll('#list button').length,5);
const audit=JSON.parse(doc.getElementById('auditData').textContent);
assert.equal(audit.schema_version,2);
assert.match(doc.getElementById('detail').textContent,/BibTeX preview/);
assert.match(doc.getElementById('detail').textContent,/var-wrong-year/);
assert.match(doc.getElementById('detail').textContent,/2024/);
assert.match(doc.getElementById('detail').textContent,/AI-suggested from title/);
assert.equal(doc.querySelector('#claimsChecked'),null);
assert.equal(doc.querySelector('option[value="rewrite"]'),null);
doc.getElementById('reviewer').value='SYNTHETIC UI TEST';
for(const id of ['identity','metadata','limitations'])doc.getElementById(id).checked=true;
doc.getElementById('action').value='approve';doc.getElementById('record').click();
assert.match(doc.getElementById('feedback').textContent,/Complete the bibliography review checks/);
assert.match(doc.getElementById('summary').textContent,/Approved 0/);
for(const id of ['format','keywords'])doc.getElementById(id).checked=true;
doc.getElementById('record').click();assert.match(doc.getElementById('summary').textContent,/Approved 1/);
doc.getElementById('saveDraft').click();
const saved=JSON.parse(dom.window.localStorage.getItem('reference-review-v2:'+audit.run_id));
assert.equal(saved.decisions[0].scope,'bibliography');assert.equal(saved.decisions[0].format_checked,true);assert.equal(saved.decisions[0].keywords_checked,true);
doc.querySelectorAll('#list button')[1].click();doc.getElementById('action').value='revise';doc.getElementById('note').value='Synthetic test: revise topic tags.';doc.getElementById('record').click();assert.match(doc.getElementById('summary').textContent,/Decisions 2/);
doc.getElementById('search').value='unmatched-synthetic-query';doc.getElementById('search').dispatchEvent(new dom.window.Event('input'));assert.equal(doc.querySelectorAll('#list button').length,0);
assert.deepEqual(errors,[]);dom.window.close();
console.log('DOM tests passed: citation/keyword preview, bibliography gate, decisions, draft persistence, correction request, search. No visual layout test.');
